apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ai-task-platform
data:
  MONGO_URI: "mongodb://root:rootpassword@mongodb:27017/ai-task-platform?authSource=admin"
  REDIS_URL: "redis://redis:6379"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  PORT: "8000"